channels:
    - conda-forge
dependencies:
    - black
    - pytest-cov
    - ipython
    - isort
    - pip
    - pre-commit
    - pytest
    - mypy
    - pytest-asyncio
    - sphinx
    - recommonmark
    - sphinx-markdown-tables
    - pip:
        - pytest-split
        - types-pyyaml
        - types-redis
        - types-tabulate

